var jwt = require('express-jwt');

var Playlist = require("./models/playlist.js");
var User = require("./models/user.js");

exports.dbUrl = '';
// if we lose connection to the database, reconnect
exports.dbOptions = {
    server: {socketOptions: {keepAlive: 300000, connectTimeoutMS: 30000}},
    replset: {socketOptions: {keepAlive: 300000, connectTimeoutMS: 30000}}
};

// secret key used for encryption, decryption and database password hashing
exports.secret = "TNo8^H4Meh06TWOROoxAsWtD_OBs[2";
// payload is the request property from which we get the user's details based on the token given to us
exports.auth = jwt({secret: this.secret, userProperty: 'payload'});

exports.checkPlaylistOwner = function () {
    return function (req, res, next) {
        Playlist.findOne({_id: req.params.id}, function (err, playlist) {
            if (err) {
                return res.status(400).json({message: err});
            } else if (!playlist) {
                return res.status(400).json({message: 'Playlist does not exist.'});
            } else {
                if (req.payload.username !== playlist.createdBy) {
                    // we cannot allow users to make changes to playlists that aren't theirs
                    return res.status(401).json({message: 'Not the playlist owner.'});
                } else {
                    // pass the found playlist to each request (so we don't have to create a new query each time)
                    req.playlist = playlist;

                    // continue middleware execution
                    next();
                }
            }
        });
    }
};

// compares the user logged in to the resource he or she is trying to edit
// and whether or not there is permission to do so
exports.checkUserEditableResource = function () {
    return function (req, res, next) {
        User.findOne({username: req.payload.username}, function (err, user) {
            if (err) {
                return res.status(400).json({message: err});
            } else if (!user) {
                return res.status(400).json({message: 'Could not find the user you passed.'});
            } else {
                if (req.payload.username !== user.username) {
                    return res.status(401).json({message: 'You do not have permission to edit this user.'});
                } else {
                    req.editingUser = user;
                    next();
                }
            }
        });
    }
};

exports.unexpectedError = function (res) {
    return res.status(400).json({message: 'An unexpected error occurred.'});
};

exports.tags = [
    "rock",
    "electronic",
    "pop",
    "alternative rock",
    "hip hop",
    "united states",
    "house",
    "jazz",
    "alternative",
    "indie",
    "electro",
    "experimental",
    "indie rock",
    "pop rock",
    "punk",
    "techno",
    "folk",
    "downtempo",
    "ambient",
    "soul",
    "germany",
    "electronica",
    "trance",
    "disco",
    "american",
    "synthpop",
    "world",
    "funk",
    "blues",
    "hardcore",
    "country",
    "dance",
    "acoustic",
    "breakbeat",
    "reggae",
    "female vocalist",
    "classic rock",
    "metal",
    "vocal",
    "latin",
    "singer-songwriter",
    "folk rock",
    "hard rock",
    "instrumental",
    "rap",
    "chill-out",
    "dub",
    "guitar",
    "new wave",
    "tech house",
    "soundtrack",
    "deep house",
    "80s",
    "french",
    "ballad",
    "industrial",
    "trip hop",
    "progressive house",
    "male vocalist",
    "minimal",
    "heavy metal",
    "90s",
    "psychedelic",
    "easy listening",
    "funk soul",
    "soft rock",
    "00s",
    "progressive rock",
    "indie pop",
    "r&b",
    "progressive trance",
    "noise",
    "drum and bass",
    "emo",
    "california",
    "british",
    "abstract",
    "intelligent dance music",
    "beautiful",
    "classic",
    "club",
    "progressive",
    "hard trance",
    "ska",
    "death metal",
    "blues-rock",
    "post rock",
    "psychedelic rock",
    "europop",
    "pop rap",
    "female",
    "classical",
    "country rock",
    "lounge",
    "future jazz",
    "euro-house",
    "los angeles",
    "italy",
    "nederland",
    "european",
    "piano",
    "garage rock",
    "acid jazz",
    "power pop",
    "hard house",
    "oldies",
    "dj",
    "canada",
    "lo-fi",
    "german",
    "70s",
    "new york",
    "bass",
    "60s",
    "remix",
    "spain",
    "chanson",
    "thrash metal",
    "fusion",
    "singer",
    "party music",
    "british pop",
    "acid",
    "dark",
    "mellow",
    "urban",
    "original",
    "art rock",
    "big beat",
    "black",
    "grunge",
    "smooth jazz",
    "italian disco",
    "alternative pop rock",
    "japan",
    "cover",
    "sexy",
    "rock 'n roll",
    "sweden",
    "jazz funk",
    "black metal",
    "rockabilly",
    "jungle music",
    "avant-garde",
    "belgium",
    "soul jazz",
    "americana",
    "shoegaze",
    "beat",
    "swing",
    "tribal house",
    "christian",
    "broken beat",
    "dancehall",
    "doom metal",
    "gothic rock",
    "beats",
    "melodic",
    "english",
    "spanish",
    "gothic",
    "happy hardcore",
    "funky",
    "uk garage",
    "england",
    "world music",
    "male",
    "tribal",
    "heavy",
    "underground",
    "swedish",
    "group",
    "ebm",
    "canadian",
    "groove",
    "latin jazz",
    "world reggae",
    "metalcore",
    "grindcore",
    "progressive metal",
    "glitch",
    "contemporary jazz",
    "mix",
    "japanese",
    "relax",
    "german pop",
    "pop punk",
    "underground hip hop",
    "stoner rock",
    "alternative country",
    "political",
    "comedy",
    "hardcore punk",
    "old school",
    "deep",
    "female vocals",
    "gospel",
    "garage",
    "london",
    "free jazz",
    "drums",
    "nu metal",
    "roots reggae",
    "post-hardcore",
    "modern classical",
    "hardstyle",
    "freestyle",
    "neo soul",
    "garage house",
    "alternative metal",
    "roots",
    "melancholia",
    "screamo",
    "funny",
    "composer",
    "bossa nova",
    "electropop",
    "smooth",
    "club dance",
    "orchestra",
    "romantic",
    "space rock",
    "hip house",
    "modern rock",
    "gabba",
    "experimental rock",
    "new age",
    "texas",
    "italian",
    "nu jazz",
    "breakcore",
    "dark wave",
    "acid house",
    "song writer",
    "psychedelic trance",
    "gangsta",
    "producer",
    "chicago",
    "underground rap",
    "solo",
    "christmas music",
    "finish",
    "southern rock",
    "traditional",
    "conscious",
    "big band",
    "power metal",
    "dream pop",
    "doo-wop",
    "dark ambient",
    "ethereal",
    "dubstep",
    "indietronica",
    "lyrics",
    "scandinavia",
    "synth",
    "radio",
    "neofolk",
    "samba",
    "guitarist",
    "spoken word",
    "up beat",
    "contemporary",
    "eurodance",
    "surf music",
    "bluegrass",
    "hardcore rap",
    "game",
    "minimal techno",
    "epic",
    "gothic metal",
    "free",
    "dance pop",
    "gangster rap",
    "salsa",
    "grime",
    "dreamy",
    "glam",
    "jazz rock",
    "celtic",
    "new beat",
    "dream",
    "modern",
    "noise rock",
    "spiritual",
    "jazz fusion",
    "italian dance",
    "math rock",
    "rave",
    "melodic death metal",
    "country blues",
    "russia",
    "symphonic rock",
    "jam",
    "voice",
    "50s",
    "slow",
    "cool jazz",
    "rock steady",
    "lyrical"
];